apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
<<<<<<< HEAD
    - image: amarbaliyan147/auth
=======
    - image: your docker username/auth
>>>>>>> master
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
<<<<<<< HEAD
    - image: amarbaliyan147/client
=======
    - image: your docker username/client
>>>>>>> master
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
